id: D92E3B19F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-28T09:31:08+00:00'
last_modified: '2022-05-30T07:58:32.353000+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    e4e0:
      image_group_id: I1PD96845
      title: འཕགས་པ་རྟེན་ཅིང་འབྲེལ་བར་འབྱུང་བ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོ།
      total_pages: 856
      order: 62
      base_file: e4e0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
