id: PFEC7DFA2
initial_creation_type: ocr
source_metadata:
  volumes:
    e5d5ed8405c34cc5b0305a0b3f7bd460:
      base_file: v062.txt
      image_group_id: I1PD96845
      title: འཕགས་པ་རྟེན་ཅིང་འབྲེལ་བར་འབྱུང་བ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོ།
      total_pages: 856
      volume_number: 62
